version: '3.7'
services:
  starter-server:
    build:
      context: ./
    command: sh -c "yarn build && yarn start"
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
    restart: on-failure 

  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: always