version: '3.7'
services:
  starter-server:
    container_name: starter-server
    environment: 
      - NODE_ENV=production
    env_file:
      - .env
    build:
      context: ./
    image: starter-server
    ports:
     - 5000:5000
    networks:
      - app-network 
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network
    restart: always
  
networks:
  app-network:
    external: true
  